### ISSUE TITLE
Cliente vê seus dispositivos

### ISSUE THREAD

**Issue by sadeoli** [TreinaDev/insurance-comparator-app#18]
- [x]  Cliente vê seus dispositivos dentro do seu perfil
- [x] Cliente clica no dispositivo e vê detalhes

Obs.:
- Exibir mensagem 'Nenhum dispositivo cadastrado' quando o cliente não tiver dispositivos
- Cadastrar dispositivo somente se estiver autenticado
- Garantir que um cliente não vê os dispositivos de outro cliente
- Lista de apólices está em outra issue

**Comment by Thalis-Freitas** [comment]
Sugestões de :
- na tela de cadastro de dispositivos acrescentar no label photos a informação de que precisam ser cadastradas 2 fotos
- corrigir equipment cadastrado no db/seeds
