### ISSUE TITLE
API - consultar meios de pagamento ativos na gestão de pagamentos e antifraude

### ISSUE THREAD

**Issue by KarinaMSakata** [TreinaDev/insurance-comparator-app#23]
(podem ser do tipo boleto bancário, pix ou cartão de crédito)

- Tipo de pagamento (id)
- nome 
- taxa por cobrança em % 
- taxa máxima em reais
- quantidade máxima de parcelas(cadastrado pela seguradora)
- desconto em caso de pagamento em uma parcela(opcional, cadastrado pela seguradora)
- Status

Validações:
- criar testes de validação de recebimento de dados da api

**Comment by Izabellyrb** [comment]
- [ ]  transformar http://localhost:4000/api/v1/ em constume configuration https://guiarails.com.br/configuring.html#custom-configuration
