### ISSUE TITLE
API - disponibilizar solicitação de compra para aprovação da seguradora na gestão de seguradoras e pacotes

### ISSUE THREAD

**Issue by alisboam** [TreinaDev/insurance-comparator-app#58]
- Refatorar teste de sistema de criar pedido
- Teste unitário para método de post_policy
- Criar os mocks para os testes

**Comment by KarinaMSakata** [comment]
Após validação do CPF:

POST para API GSP, end-point "POST /api/v1/policies" que envia as informações da da compra para a equipe 1 criar a apólice.

status da order muda "insurance_company_approval"

Resumo de atributos:

{
"client_name": "Maria Alves",
"client_registration_number": "99950033340",
"client_email": "[mariaalves@email.com](mailto:mariaalves@email.com)",
"policy_period": 12,
"order_id": 1,
"package_id": 1,
"insurance_company_id": 1,
"equipment_id": 1
}
